resources:
  - ../../base
commonLabels:
  environment: prod
namespace: prod
patches:
  - target:
      kind: Deployment
      name: nginx-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
configMapGenerator:
  - name: nginx-config
    literals:
      - ENVIRONMENT=prod
