apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nginx
  namespace: dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/arbitrarymahi/argocd/'
    path: nginx/overlays/dev
    targetRevision: HEAD
    kustomize:
      namePrefix: dev-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
