bases:
  - ../../base
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  environment: dev
namespace: dev-namespace
patches:
  - target:
      kind: Deployment
      name: nginx-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
configMapGenerator:
  - name: nginx-config
    literals:
      - ENVIRONMENT=dev
