resources:
- ../../base
namespace: dev
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: nginx-app
configMapGenerator:
- literals:
  - ENVIRONMENT=dev
  name: nginx-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    environment: dev
