apiVersion: batch/v1
kind: Job
metadata:
    generateName: post-sync-flock-job
    annotations: 
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed

spec:
    template:
        spec:
            containers:
            - name: flock-msg
              image: curlimages/curl
              command:
                - "curl"
                - "-X"
                - "POST"
                - "https://api.flock.com/hooks/sendMessage/9f12ee72-35dc-44c2-a53c-96cb67c3ca6a"
                - "-H"
                - "Content-Type: application/json"
                - "-d"
                - '{"text": "succesfully synced dev-nginx application"}'
            
            restartPolicy: Never
        backoffLimit: 2
