apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-nginx
  namespace: prod
spec:
  project: default
  source:
    repoURL: 'https://github.com/arbitrarymahi/argocd'
    path: nginx/overlays/prod
    targetRevision: HEAD
    kustomize:
      namePrefix: prod-
  destination:
    server: 'https://34.31.156.179'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
