apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-multicluster
  namespace: argocd
spec:
  project: default #argo project in which this application will be grouped
  source:
    repoURL: https://github.com/arbitrarymahi/argocd.git
    targetRevision: HEAD
    path: multicluster-app
  destination: 
    name: gke-c2
    namespace: multicluster-argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
